apiVersion: v2
appVersion: 0.27.3
name: trivy-operator
description: A Giant Swarm App for trivy-operator, the cluster security tool from Aqua Security.
home: https://github.com/giantswarm/trivy-operator-app
icon: https://s.giantswarm.io/app-icons/trivy/1/light.svg
maintainers:
  - name: Giant Swarm applications team
    url: https://github.com/giantswarm/trivy-operator-app
sources:
  - https://github.com/aquasecurity/trivy-operator
version: 0.12.1
dependencies:
  - name: trivy-operator
    version: "0.31.0"
annotations:
  io.giantswarm.application.audience: all
  io.giantswarm.application.managed: "true"
  io.giantswarm.application.team: shield
  #   branch: my-branch # Used through .Chart.Annotations.branch (This is not replaced automatically)
  #   commit: f00bar # Used through .Chart.Annotations.commit (This is not replaced automatically)
